services:
  # A Docker web service
  - type: web
    name: alist
    env: docker
    repo: https://github.com/zzy-ac/npm-cdn-docker.git # optional
    region: singapore # optional (defaults to oregon)
    plan: free # optional (defaults to starter)
    healthCheckPath: /
    envVars:
      - key: PORT
        value: 80
